/** The recommended number of air changes per hour for a zone to be considered to have optimal climate control. */
export const RECOMMENDED_ACH = 5;

/** The base amount of water vapor (in kg) that plants are expected to produce per square meter per hour, which dehumidifiers must counteract. */
export const BASE_DEHUMIDIFICATION_LOAD_PER_M2_PER_H = 0.02;

/** The required rate of CO₂ injection (in ppm) per hour per square meter needed to maintain optimal levels against plant consumption and natural leakage. */
export const BASE_CO2_INJECTION_PPM_PER_TICK_PER_M2 = 5;

/** The default temperature (in Celsius) of the outside world that the zone's internal temperature will naturally drift towards. */
export const AMBIENT_TEMP_C = 20;

/** The default relative humidity (as a fraction from 0 to 1) of the outside world. */
export const AMBIENT_HUMIDITY_RH = 0.5;

/** The default CO₂ concentration (in parts per million) of the outside world. */
export const AMBIENT_CO2_PPM = 400;

/** A multiplier determining how quickly a zone's temperature normalizes towards the ambient temperature each hour. */
export const TEMP_NORMALIZATION_FACTOR = 0.1;

/** A multiplier determining how quickly a zone's humidity normalizes towards the ambient humidity each hour. */
export const HUMIDITY_NORMALIZATION_FACTOR = 0.05;

/** A multiplier determining how quickly a zone's CO₂ level normalizes towards the ambient CO₂ level each hour. */
export const CO2_NORMALIZATION_FACTOR = 0.1;

/** A conversion factor that determines how much a lamp's power consumption (in kW) contributes to an increase in the zone's temperature (°C) each hour. */
export const LAMP_HEAT_FACTOR = 0.5;

/** A conversion factor that determines how much a climate unit's cooling capacity (in kW) contributes to a decrease in the zone's temperature (°C) each hour. */
export const COOLING_CAPACITY_FACTOR = 0.8;

/** A conversion factor for the waste heat generated by a dehumidifier, determining how much its power consumption (in kW) increases the zone's temperature (°C) each hour. */
export const DEHUMIDIFIER_HEAT_FACTOR = 0.2;

/** The amount of relative humidity (as a fraction from 0 to 1) that a single plant adds to the zone each hour through transpiration. */
export const PLANT_TRANSPIRATION_RH_PER_PLANT = 0.00005;

/**
 * Approximate saturated water vapour density of air at 20 °C in kg·m⁻³. Used to convert
 * humidifier/dehumidifier water mass flow into relative humidity deltas for a zone volume.
 */
export const SATURATION_VAPOR_DENSITY_KG_PER_M3 = 0.0173;

/** The amount of CO₂ (in ppm) that a single plant removes from the zone each hour during photosynthesis. */
export const PLANT_CO2_CONSUMPTION_PPM_PER_PLANT = 0.2;

/** The base amount of durability that every active device loses each hour from wear and tear. */
export const BASE_DURABILITY_DECAY_PER_TICK = 0.00002;

/** The underlying random probability that any given plant might contract a disease each hour. */
export const BASE_DISEASE_CHANCE_PER_TICK = 0.0001;
