name: Data Validation

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  quality-gate:
    name: Run pnpm check
    runs-on: ubuntu-latest
    steps:
      - &checkout
        name: Checkout repository
        uses: actions/checkout@v4

      - &setup-pnpm
        name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.17.0

      - &setup-node
        name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - &install
        name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run aggregated quality checks
        run: pnpm check

  audit:
    name: Audit dependencies
    runs-on: ubuntu-latest
    steps:
      - *checkout
      - *setup-pnpm
      - *setup-node
      - *install

      - name: Run security audit
        run: pnpm audit:run
